// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Event
    {
        public const string Codename = "event";
        public const string DateCodename = "date";
        public const string DescriptionCodename = "description";
        public const string GalleryCodename = "gallery";
        public const string NameCodename = "name";
        public const string SlugCodename = "slug";
        public const string VenueCodename = "venue";

        public DateTime? Date { get; set; }
        public string Description { get; set; }
        public IEnumerable<IAsset> Gallery { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> Venue { get; set; }
    }
}