// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Facility
    {
        public const string Codename = "facility";
        public const string LabelCodename = "label";
        public const string StyleCodename = "style";

        public string Label { get; set; }
        public string Style { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}