// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace HeadlessCreator.Models.ContentTypes
{
    public partial class Venue
    {
        public const string Codename = "venue";
        public const string DescriptionCodename = "description";
        public const string FacilitiesCodename = "facilities";
        public const string GalleryCodename = "gallery";
        public const string NameCodename = "name";
        public const string SlugCodename = "slug";

        public string Description { get; set; }
        public IEnumerable<object> Facilities { get; set; }
        public IEnumerable<IAsset> Gallery { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}